#define UINT4_SIZE  16
#define UINT3_SIZE  12
#define UINT2_SIZE  8
#define UINT_SIZE   4
#define FLOAT4_SIZE 16
#define FLOAT3_SIZE 12
#define FLOAT2_SIZE 8
#define FLOAT_SIZE  4

#define MATRIX4X4_SIZE 64
#define MATRIX3X3_SIZE 36

int CLIPSIZE = MAX_MODEL_KEYFRAMES * MAX_MODEL_TRANSFORMS;